# Generated by Django 5.0.6 on 2024-06-18 13:00

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("networth_tracker", "0003_account_allocation_cash_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customuser",
            name="date_joined",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2024, 6, 18, 13, 0, 50, 214707, tzinfo=datetime.timezone.utc
                ),
                verbose_name="date joined",
            ),
        ),
        migrations.CreateModel(
            name="Etf",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("ticker", models.CharField(max_length=100)),
                ("fund_name", models.CharField(max_length=100)),
                ("units_held", models.FloatField()),
                ("average_cost", models.FloatField()),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="EtfTransaction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "transaction_type",
                    models.PositiveSmallIntegerField(choices=[(0, "Buy"), (1, "Sell")]),
                ),
                ("order_date", models.DateField()),
                ("units", models.FloatField()),
                ("order_cost", models.FloatField()),
                ("brokerage", models.FloatField(blank=True, null=True)),
                (
                    "etf",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="networth_tracker.etf"
                    ),
                ),
            ],
        ),
    ]
