# Generated by Django 5.0.6 on 2024-06-21 12:35

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("networth_tracker", "0004_alter_customuser_date_joined_etf_etftransaction"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customuser",
            name="date_joined",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2024, 6, 21, 12, 35, 49, 884595, tzinfo=datetime.timezone.utc
                ),
                verbose_name="date joined",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="account",
            unique_together={("user",)},
        ),
    ]
