# Generated by Django 5.0.6 on 2024-06-25 11:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("networth_tracker", "0006_remove_customuser_date_joined_account_created_at_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Superannuation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="created at")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="updated at")),
                ("provider", models.CharField(max_length=100)),
                ("investment_plan", models.CharField(max_length=100)),
                ("balance", models.FloatField()),
                ("market_returns", models.FloatField()),
                ("voluntary_contributions", models.FloatField()),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
